name: release-pls

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: release-please-action
        uses: google-github-actions/release-please-action@v3.0.0
        with:
          release-type: simple
          package-name: hello-latex

      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: make -C build
          
      - name: Release
        if: ${{ steps.release.outputs.release_created }}
        uses: softprops/action-gh-release@v1
        with:
          files: build/template.pdf
