name: release-pls

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: release
        uses: google-github-actions/release-please-action@v3.0.0
        with:
          release-type: simple
          package-name: hello-latex

      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}
      - name: Install LaTeX
        run: sudo apt-get install texlive-latex-base -y
        if: ${{ steps.release.outputs.release_created }}
      - name: Build
        run: make -C build
        if: ${{ steps.release.outputs.release_created }}
      - name: Append PDF to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/template.pdf
          tag: ${{ steps.release.outputs.tag_name }}
        if: ${{ steps.release.outputs.release_created }}
