name: release-pls

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: google-github-actions/release-please-action@v3.0.0
        id: release
        with:
          release-type: simple
          package-name: hello-latex

      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}
      - name: Setup Tectonic
        uses: wtfjoke/setup-tectonic@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
      - name: Test compile
        run: tectonic src/template.tex --outdir build
        if: ${{ steps.release.outputs.release_created }}
      - name: Append PDF to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/template.pdf
          tag: ${{ steps.release.outputs.tag_name }}
        if: ${{ steps.release.outputs.release_created }}
